services:
  - type: web
    name: cbevent-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: cbevent_db
      - key: DB_PORT
        value: 3306
      - key: JWT_SECRET
        value: supersecret123
      - key: CORS_ORIGIN
        value: https://sampleone.in,https://www.sampleone.in
      - key: CLOUDINARY_CLOUD_NAME
        value: dly16icr8
      - key: CLOUDINARY_API_KEY
        value: 983344653426663
      - key: CLOUDINARY_API_SECRET
        value: N_qZKPSDyTeJnjJUz_rygkx3lno
      - key: CLOUDINARY_URL
        value: cloudinary://983344653426663:N_qZKPSDyTeJnjJUz_rygkx3lno@dly16icr8 